[build]
  command = "npm run build -- --configuration production"
  publish = "dist/my-store"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[plugins]
  # vacío a propósito para desactivar plugins automáticos
